Repository Volgarenok/spbspu-labs-2023-aap-a, pull requests merged in 2023-12, with the labels that each got.

#111 skopchenko.alexander/p1
  skopchenko.alexander/P1/cntmax.cpp
  skopchenko.alexander/P1/cntmax.hpp
  skopchenko.alexander/P1/incseq.cpp
  skopchenko.alexander/P1/incseq.hpp
  skopchenko.alexander/P1/main.cpp
  skopchenko.alexander/P1/negmul.cpp
  skopchenko.alexander/P1/negmul.hpp
Labels: fine, black-mark

#80 rebdev.pavel/P4
  rebdev.pavel/P4/main.cpp
  rebdev.pavel/P4/matrix.cpp
  rebdev.pavel/P4/matrix.hpp
  rebdev.pavel/P4/readFromFile.cpp
  rebdev.pavel/P4/readFromFile.hpp
Labels: fine

#85 zhalilov.rail/P4
  zhalilov.rail/P4/countNonZeroDiags.cpp
  zhalilov.rail/P4/countNonZeroDiags.hpp
  zhalilov.rail/P4/inputMatrix.cpp
  zhalilov.rail/P4/inputMatrix.hpp
  zhalilov.rail/P4/main.cpp
Labels: fine

#84 piyavkin.anton/P4
  piyavkin.anton/P4/checklowertriangularmatrix.cpp
  piyavkin.anton/P4/checklowertriangularmatrix.hpp
  piyavkin.anton/P4/checknonzero.cpp
  piyavkin.anton/P4/checknonzero.hpp
  piyavkin.anton/P4/inputarray.cpp
  piyavkin.anton/P4/inputarray.hpp
  piyavkin.anton/P4/main.cpp
Labels: fine

#88 Namestnikov.kirill/p4
  namestnikov.kirill/P4/input_array.cpp
  namestnikov.kirill/P4/input_array.hpp
  namestnikov.kirill/P4/main.cpp
  namestnikov.kirill/P4/saddle_points_counter.cpp
  namestnikov.kirill/P4/saddle_points_counter.hpp
Labels: fine

#79 strelyaev.roman/P4
  strelyaev.roman/P4/clock_matrix.cpp
  strelyaev.roman/P4/clock_matrix.h
  strelyaev.roman/P4/main.cpp
  strelyaev.roman/P4/matrix.cpp
  strelyaev.roman/P4/matrix.h
Labels: fine

#65 Vyzhanov.daniil/p1
  vyzhanov.daniil/P1/CompositionOfCharacteristics.cpp
  vyzhanov.daniil/P1/CompositionOfCharacteristics.hpp
  vyzhanov.daniil/P1/CountAfterMax.cpp
  vyzhanov.daniil/P1/CountAfterMax.hpp
  vyzhanov.daniil/P1/CountEqualSumTwoPrev.cpp
  vyzhanov.daniil/P1/CountEqualSumTwoPrev.hpp
  vyzhanov.daniil/P1/PrevMoreNextLessCheck.cpp
  vyzhanov.daniil/P1/PrevMoreNextLessCheck.hpp
  vyzhanov.daniil/P1/main.cpp
Labels: fine, additional-task, 4/5

#87 gladyshev.matvey/P4
  gladyshev.matvey/P4/main.cpp
  gladyshev.matvey/P4/makematrix.cpp
  gladyshev.matvey/P4/makematrix.h
  gladyshev.matvey/P4/matrixchecktri.cpp
  gladyshev.matvey/P4/matrixchecktri.h
  gladyshev.matvey/P4/zeromatrix.cpp
  gladyshev.matvey/P4/zeromatrix.h
Labels: fine

#60 sakovskaia.maiia/P1
  sakovskaia.maiia/P1/main.cpp
  sakovskaia.maiia/P1/sequence_counter.cpp
  sakovskaia.maiia/P1/sequence_counter.hpp
Labels: fine

#68 Shabalin.dmitrij/p1
  shabalin.dmitrij/P1/loc_max.cpp
  shabalin.dmitrij/P1/loc_max.hpp
  shabalin.dmitrij/P1/main.cpp
Labels: fine

#97 chistyakov.vladislav/P4
  chistyakov.vladislav/P4/countLocalMinimums.cpp
  chistyakov.vladislav/P4/countLocalMinimums.hpp
  chistyakov.vladislav/P4/inputArray.cpp
  chistyakov.vladislav/P4/inputArray.hpp
  chistyakov.vladislav/P4/main.cpp
  chistyakov.vladislav/P4/min.cpp
  chistyakov.vladislav/P4/min.hpp
Labels: fine

#93 spiridonov.mikhail/P4
  spiridonov.mikhail/P4/getMinimumSum.cpp
  spiridonov.mikhail/P4/getMinimumSum.hpp
  spiridonov.mikhail/P4/main.cpp
  spiridonov.mikhail/P4/readMatrix.cpp
  spiridonov.mikhail/P4/readMatrix.hpp
Labels: fine

#67 belokurskaya.sofia/P1
  belokurskaya.sofia/P1/counter_of_numbers_equal_to_the_maximum.cpp
  belokurskaya.sofia/P1/counter_of_numbers_equal_to_the_maximum.hpp
  belokurskaya.sofia/P1/main.cpp
Labels: fine

#98 zakozhurnikova.kristina/P4
  zakozhurnikova.kristina/P4/file_operation.cpp
  zakozhurnikova.kristina/P4/file_operation.h
  zakozhurnikova.kristina/P4/main.cpp
  zakozhurnikova.kristina/P4/matrix_operation.cpp
  zakozhurnikova.kristina/P4/matrix_operation.h
Labels: fine, 4/5

#70 lopatina.sofia/P1
  lopatina.sofia/P1/loc_max_counter.cpp
  lopatina.sofia/P1/loc_max_counter.hpp
  lopatina.sofia/P1/main.cpp
Labels: fine, 4/5

#81 stepanov.gena/P1
  stepanov.gena/P1/main.cpp
  stepanov.gena/P1/sequence_counter_aft_max.cpp
  stepanov.gena/P1/sequence_counter_aft_max.hpp
  stepanov.gena/P1/sequence_counter_mon_inc.cpp
  stepanov.gena/P1/sequence_counter_mon_inc.hpp
Labels: fine, 2/5

#94 grechishnikov.roman/p4
  grechishnikov.roman/P4/countIn.cpp
  grechishnikov.roman/P4/countIn.hpp
  grechishnikov.roman/P4/inputMatrix.cpp
  grechishnikov.roman/P4/inputMatrix.hpp
  grechishnikov.roman/P4/main.cpp
Labels: fine, 4/5

#101 arakelyan.daniil/p4
  arakelyan.daniil/P4/input_output_matrix.cpp
  arakelyan.daniil/P4/input_output_matrix.hpp
  arakelyan.daniil/P4/main.cpp
  arakelyan.daniil/P4/matrix_operations.cpp
  arakelyan.daniil/P4/matrix_operations.hpp
Labels: fine

#135 treskina.anastasiya/P0
  treskina.anastasiya/P0/main.cpp
Labels: fine

#92 erohin.vladimir/P4
  erohin.vladimir/P4/fill_circle.cpp
  erohin.vladimir/P4/fill_circle.hpp
  erohin.vladimir/P4/main.cpp
  erohin.vladimir/P4/max_main_diagonal.cpp
  erohin.vladimir/P4/max_main_diagonal.hpp
  erohin.vladimir/P4/read_print_matrix.cpp
  erohin.vladimir/P4/read_print_matrix.hpp
Labels: fine, additional-task, 4/5

#119 zhalilov.rail/P3
  zhalilov.rail/P3/countDiffSymbs.cpp
  zhalilov.rail/P3/countDiffSymbs.hpp
  zhalilov.rail/P3/findCommonestSymbs.cpp
  zhalilov.rail/P3/findCommonestSymbs.hpp
  zhalilov.rail/P3/inputString.cpp
  zhalilov.rail/P3/inputString.hpp
  zhalilov.rail/P3/main.cpp
Labels: fine, additional-task

#144 lebedev.anton/P1
  lebedev.anton/P1/inc_seq.cpp
  lebedev.anton/P1/inc_seq.hpp
  lebedev.anton/P1/main.cpp
  lebedev.anton/P1/sub_max.cpp
  lebedev.anton/P1/sub_max.hpp
Labels: fine
