Repository Volgarenok/spbspu-labs-2023-aap-a, pull requests merged in 2024-01, with the labels that each got.

#82 chernov.artem/p1
  chernov.artem/P1/almost_max.cpp
  chernov.artem/P1/almost_max.hpp
  chernov.artem/P1/main.cpp
  chernov.artem/P1/piftriples_counter.cpp
  chernov.artem/P1/piftriples_counter.hpp
Labels: fine, black-mark, 2/5

#125 Novokhatskiy.danil/P3
  novokhatskiy.danil/P3/deleteLatinLetters.cpp
  novokhatskiy.danil/P3/deleteLatinLetters.hpp
  novokhatskiy.danil/P3/inputString.cpp
  novokhatskiy.danil/P3/inputString.hpp
  novokhatskiy.danil/P3/main.cpp
Labels: fine

#113 Nikitov.dmitriy/P3
  nikitov.dmitriy/P3/check_matches.cpp
  nikitov.dmitriy/P3/check_matches.hpp
  nikitov.dmitriy/P3/input_array.cpp
  nikitov.dmitriy/P3/input_array.hpp
  nikitov.dmitriy/P3/main.cpp
Labels: fine

#116 rebdev.pavel/P3
  rebdev.pavel/P3/main.cpp
  rebdev.pavel/P3/stringConvert.cpp
  rebdev.pavel/P3/stringConvert.hpp
  rebdev.pavel/P3/stringInput.cpp
  rebdev.pavel/P3/stringInput.hpp
Labels: fine

#126 baranov.pavel/P3
  baranov.pavel/P3/deleteDigits.cpp
  baranov.pavel/P3/deleteDigits.hpp
  baranov.pavel/P3/inputString.cpp
  baranov.pavel/P3/inputString.hpp
  baranov.pavel/P3/main.cpp
Labels: fine

#128 zakozhurnikova.kristina/P3
  zakozhurnikova.kristina/P3/main.cpp
  zakozhurnikova.kristina/P3/removeSpaces.cpp
  zakozhurnikova.kristina/P3/removeSpaces.h
  zakozhurnikova.kristina/P3/stringOperations.cpp
  zakozhurnikova.kristina/P3/stringOperations.h
Labels: fine, 3/5

#115 strelyaev.roman/P3
  strelyaev.roman/P3/extendstring.cpp
  strelyaev.roman/P3/extendstring.h
  strelyaev.roman/P3/main.cpp
Labels: fine

#118 isaychev.vladislav/P3
  isaychev.vladislav/P3/addLat.cpp
  isaychev.vladislav/P3/addLat.hpp
  isaychev.vladislav/P3/extractChars.cpp
  isaychev.vladislav/P3/extractChars.hpp
  isaychev.vladislav/P3/inputString.cpp
  isaychev.vladislav/P3/inputString.hpp
  isaychev.vladislav/P3/main.cpp
Labels: fine

#103 belokurskaya.sofia/P4
  belokurskaya.sofia/P4/main.cpp
  belokurskaya.sofia/P4/process_matrix.cpp
  belokurskaya.sofia/P4/process_matrix.hpp
Labels: fine

#124 gladyshev.matvey/P3
  gladyshev.matvey/P3/allocatememory.cpp
  gladyshev.matvey/P3/allocatememory.h
  gladyshev.matvey/P3/createarray.cpp
  gladyshev.matvey/P3/createarray.h
  gladyshev.matvey/P3/inputarray.cpp
  gladyshev.matvey/P3/inputarray.h
  gladyshev.matvey/P3/main.cpp
Labels: fine

#130 Namestnikov.kirill/p3
  namestnikov.kirill/P3/input_string.cpp
  namestnikov.kirill/P3/input_string.hpp
  namestnikov.kirill/P3/main.cpp
  namestnikov.kirill/P3/unique_sym_array.cpp
  namestnikov.kirill/P3/unique_sym_array.hpp
Labels: fine

#129 piyavkin.anton/P3
  piyavkin.anton/P3/createlinemissinglatinletters.cpp
  piyavkin.anton/P3/createlinemissinglatinletters.hpp
  piyavkin.anton/P3/inputline.cpp
  piyavkin.anton/P3/inputline.hpp
  piyavkin.anton/P3/main.cpp
Labels: fine

#132 marishin.leonid/P3
  marishin.leonid/P3/inputstring.cpp
  marishin.leonid/P3/inputstring.hpp
  marishin.leonid/P3/main.cpp
  marishin.leonid/P3/modifystring.cpp
  marishin.leonid/P3/modifystring.hpp
Labels: fine
