Repository Volgarenok/spbspu-labs-2023-aap-a, pull requests merged in 2024-02, with the labels that each got.

#117 grechishnikov.roman/P3
  grechishnikov.roman/P3/countUnique.cpp
  grechishnikov.roman/P3/countUnique.hpp
  grechishnikov.roman/P3/inputStr.cpp
  grechishnikov.roman/P3/inputStr.hpp
  grechishnikov.roman/P3/main.cpp
Labels: fine

#99 sivkov.filipp/P4
  sivkov.filipp/P4/localMax.cpp
  sivkov.filipp/P4/localMax.hpp
  sivkov.filipp/P4/main.cpp
  sivkov.filipp/P4/matrix.cpp
  sivkov.filipp/P4/matrix.hpp
Labels: fine, 3/5

#131 zaitsev.vladimir/P3
  zaitsev.vladimir/P3/input.cpp
  zaitsev.vladimir/P3/input.h
  zaitsev.vladimir/P3/main.cpp
  zaitsev.vladimir/P3/unique_symbols.cpp
  zaitsev.vladimir/P3/unique_symbols.h
Labels: fine

#161 serter.tugce/P0
  serter.tugce/P0/main.cpp
Labels: fine

#141 erohin.vladimir/P3
  erohin.vladimir/P3/input_string.cpp
  erohin.vladimir/P3/input_string.hpp
  erohin.vladimir/P3/main.cpp
  erohin.vladimir/P3/replace_symbol.cpp
  erohin.vladimir/P3/replace_symbol.hpp
  erohin.vladimir/P3/resize_string.cpp
  erohin.vladimir/P3/resize_string.hpp
  erohin.vladimir/P3/unite_string.cpp
  erohin.vladimir/P3/unite_string.hpp
Labels: fine

#142 ishmuratov.eric/P4
  ishmuratov.eric/P4/main.cpp
  ishmuratov.eric/P4/matrix_input.cpp
  ishmuratov.eric/P4/matrix_input.hpp
  ishmuratov.eric/P4/numrow_check.cpp
  ishmuratov.eric/P4/numrow_check.hpp
  ishmuratov.eric/P4/trimatrix_check.cpp
  ishmuratov.eric/P4/trimatrix_check.hpp
Labels: fine

#152 kovtun.alexander/P4
  kovtun.alexander/P4/equal_nums_counter.cpp
  kovtun.alexander/P4/equal_nums_counter.h
  kovtun.alexander/P4/main.cpp
  kovtun.alexander/P4/read_to_array.cpp
  kovtun.alexander/P4/read_to_array.h
  kovtun.alexander/P4/transform_matrix.cpp
  kovtun.alexander/P4/transform_matrix.h
Labels: fine

#140 vyzhanov.daniil/P4
  vyzhanov.daniil/P4/CheckLowerTriangle.cpp
  vyzhanov.daniil/P4/CheckLowerTriangle.hpp
  vyzhanov.daniil/P4/CountRowsWithoutRepeat.cpp
  vyzhanov.daniil/P4/CountRowsWithoutRepeat.hpp
  vyzhanov.daniil/P4/CreateMatrix.cpp
  vyzhanov.daniil/P4/CreateMatrix.hpp
  vyzhanov.daniil/P4/main.cpp
Labels: fine

#120 arakelyan.daniil/p3
  arakelyan.daniil/P3/difLetters.cpp
  arakelyan.daniil/P3/difLetters.hpp
  arakelyan.daniil/P3/difLettersInTwoLines.cpp
  arakelyan.daniil/P3/difLettersInTwoLines.hpp
  arakelyan.daniil/P3/inputLine.cpp
  arakelyan.daniil/P3/inputLine.hpp
  arakelyan.daniil/P3/main.cpp
Labels: fine

#160 lebedev.anton/P4
  lebedev.anton/P4/cnt_nzr_dig.cpp
  lebedev.anton/P4/cnt_nzr_dig.hpp
  lebedev.anton/P4/input_array.cpp
  lebedev.anton/P4/input_array.hpp
  lebedev.anton/P4/main.cpp
  lebedev.anton/P4/min_sum_sdg.cpp
  lebedev.anton/P4/min_sum_sdg.hpp
Labels: fine

#164 Lopatina.sofia/p4
  lopatina.sofia/P4/count_diag_nzero.cpp
  lopatina.sofia/P4/count_diag_nzero.hpp
  lopatina.sofia/P4/input_array.cpp
  lopatina.sofia/P4/input_array.hpp
  lopatina.sofia/P4/is_lowertri_matrix.cpp
  lopatina.sofia/P4/is_lowertri_matrix.hpp
  lopatina.sofia/P4/main.cpp
Labels: fine, 4/5

#122 Belokurskaya.sofia/p3
  belokurskaya.sofia/P3/main.cpp
  belokurskaya.sofia/P3/reading_a_string.cpp
  belokurskaya.sofia/P3/reading_a_string.hpp
  belokurskaya.sofia/P3/transform_string.cpp
  belokurskaya.sofia/P3/transform_string.hpp
Labels: fine

#147 Stepanov.gena/p4
  stepanov.gena/P4/count_local_min.cpp
  stepanov.gena/P4/count_local_min.hpp
  stepanov.gena/P4/find_max_row.cpp
  stepanov.gena/P4/find_max_row.hpp
  stepanov.gena/P4/input_array.cpp
  stepanov.gena/P4/input_array.hpp
  stepanov.gena/P4/is_min.cpp
  stepanov.gena/P4/is_min.hpp
  stepanov.gena/P4/main.cpp
  stepanov.gena/P4/most_long_sequence.cpp
  stepanov.gena/P4/most_long_sequence.hpp
Labels: fine, 4/5

#162 chernov.artem/P4
  chernov.artem/P4/countNonZeroDiagonals.cpp
  chernov.artem/P4/countNonZeroDiagonals.hpp
  chernov.artem/P4/incrementCirclesInMatrix.cpp
  chernov.artem/P4/incrementCirclesInMatrix.hpp
  chernov.artem/P4/main.cpp
  chernov.artem/P4/readMatrix.cpp
  chernov.artem/P4/readMatrix.hpp
  chernov.artem/P4/writeMatrix.cpp
  chernov.artem/P4/writeMatrix.hpp
Labels: fine, 4/5

#95 petuhov.kirill/P4
  petuhov.kirill/P4/fillMatrix.cpp
  petuhov.kirill/P4/fillMatrix.hpp
  petuhov.kirill/P4/islowertriangular.cpp
  petuhov.kirill/P4/islowertriangular.hpp
  petuhov.kirill/P4/main.cpp
Labels: fine, 3/5

#176 ishmuratov.eric/P3
  ishmuratov.eric/P3/has_rep_digit.cpp
  ishmuratov.eric/P3/has_rep_digit.hpp
  ishmuratov.eric/P3/has_rep_symbol.cpp
  ishmuratov.eric/P3/has_rep_symbol.hpp
  ishmuratov.eric/P3/input_string.cpp
  ishmuratov.eric/P3/input_string.hpp
  ishmuratov.eric/P3/main.cpp
Labels: fine

#174 lebedev.anton/P3
  lebedev.anton/P3/frq_top.cpp
  lebedev.anton/P3/frq_top.hpp
  lebedev.anton/P3/input_string.cpp
  lebedev.anton/P3/input_string.hpp
  lebedev.anton/P3/main.cpp
  lebedev.anton/P3/upp_low.cpp
  lebedev.anton/P3/upp_low.hpp
Labels: fine

#173 sivkov.filipp/P3
  sivkov.filipp/P3/copyNum.cpp
  sivkov.filipp/P3/copyNum.hpp
  sivkov.filipp/P3/inputString.cpp
  sivkov.filipp/P3/inputString.hpp
  sivkov.filipp/P3/main.cpp
  sivkov.filipp/P3/removing_spaces.cpp
  sivkov.filipp/P3/removing_spaces.hpp
  sivkov.filipp/P3/removing_vowels.cpp
  sivkov.filipp/P3/removing_vowels.hpp
Labels: fine, additional-task

#145 skuratov.danil/P3
  skuratov.danil/P3/main.cpp
  skuratov.danil/P3/mergeTwoLines.cpp
  skuratov.danil/P3/mergeTwoLines.h
  skuratov.danil/P3/removeDuplicate.cpp
  skuratov.danil/P3/removeDuplicate.h
  skuratov.danil/P3/transformInputString.cpp
  skuratov.danil/P3/transformInputString.h
Labels: fine

#187 stepanov.gena/p3
  stepanov.gena/P3/inputArray.cpp
  stepanov.gena/P3/inputArray.hpp
  stepanov.gena/P3/isConsonat.cpp
  stepanov.gena/P3/isConsonat.hpp
  stepanov.gena/P3/main.cpp
  stepanov.gena/P3/removeVowels.cpp
  stepanov.gena/P3/removeVowels.hpp
  stepanov.gena/P3/replaceStringToLow.cpp
  stepanov.gena/P3/replaceStringToLow.hpp
Labels: fine, 4/5

#172 lopatina.sofia/p3
  lopatina.sofia/P3/add_numbers.cpp
  lopatina.sofia/P3/add_numbers.hpp
  lopatina.sofia/P3/exclude_common_letters.cpp
  lopatina.sofia/P3/exclude_common_letters.hpp
  lopatina.sofia/P3/expand_array.cpp
  lopatina.sofia/P3/expand_array.hpp
  lopatina.sofia/P3/main.cpp
Labels: fine, 4/5

#143 zhalilov.rail/T1
  zhalilov.rail/T1/base-types.hpp
  zhalilov.rail/T1/circle.cpp
  zhalilov.rail/T1/circle.hpp
  zhalilov.rail/T1/inputShapesSource.cpp
  zhalilov.rail/T1/inputShapesSource.hpp
  zhalilov.rail/T1/isoScale.cpp
  zhalilov.rail/T1/isoScale.hpp
  zhalilov.rail/T1/main.cpp
  zhalilov.rail/T1/outputShapesSource.cpp
  zhalilov.rail/T1/outputShapesSource.hpp
  zhalilov.rail/T1/polygon.cpp
  zhalilov.rail/T1/polygon.hpp
  zhalilov.rail/T1/rectangle.cpp
  zhalilov.rail/T1/rectangle.hpp
  zhalilov.rail/T1/shape.cpp
  zhalilov.rail/T1/shape.hpp
Labels: fine, 3/5

#148 Novokhatskiy.danil/T1
  novokhatskiy.danil/T1/base-types.hpp
  novokhatskiy.danil/T1/ellipse.cpp
  novokhatskiy.danil/T1/ellipse.hpp
  novokhatskiy.danil/T1/inputShapes.cpp
  novokhatskiy.danil/T1/inputShapes.hpp
  novokhatskiy.danil/T1/isoScale.cpp
  novokhatskiy.danil/T1/isoScale.hpp
  novokhatskiy.danil/T1/main.cpp
  novokhatskiy.danil/T1/outputShapes.cpp
  novokhatskiy.danil/T1/outputShapes.hpp
  novokhatskiy.danil/T1/rectangle.cpp
  novokhatskiy.danil/T1/rectangle.hpp
  novokhatskiy.danil/T1/ring.cpp
  novokhatskiy.danil/T1/ring.hpp
  novokhatskiy.danil/T1/shape.hpp
Labels: fine, 3/5

#186 kovtun.alexander/P3
  kovtun.alexander/P3/convert_to_lowercase.cpp
  kovtun.alexander/P3/convert_to_lowercase.h
  kovtun.alexander/P3/main.cpp
  kovtun.alexander/P3/read_string.cpp
  kovtun.alexander/P3/read_string.h
  kovtun.alexander/P3/strings_merge.cpp
  kovtun.alexander/P3/strings_merge.h
Labels: fine

#157 strelyaev.roman/T1
  strelyaev.roman/P3/extendstring.cpp
  strelyaev.roman/P3/extendstring.h
  strelyaev.roman/P3/main.cpp
  strelyaev.roman/T1/base-types.hpp
  strelyaev.roman/T1/inputShapes.cpp
  strelyaev.roman/T1/inputShapes.hpp
  strelyaev.roman/T1/main.cpp
  strelyaev.roman/T1/parallelogram.cpp
  strelyaev.roman/T1/parallelogram.hpp
  strelyaev.roman/T1/rectangle.cpp
  strelyaev.roman/T1/rectangle.hpp
  strelyaev.roman/T1/shape.cpp
  strelyaev.roman/T1/shape.hpp
  strelyaev.roman/T1/stringProc.cpp
  strelyaev.roman/T1/stringProc.hpp
  strelyaev.roman/T1/triangle.cpp
  strelyaev.roman/T1/triangle.hpp
  strelyaev.roman/common/getString.cpp
  strelyaev.roman/common/getString.hpp
Labels: fine, 3/5

#151 erohin.vladimir/T1
  erohin.vladimir/T1/base-types.hpp
  erohin.vladimir/T1/complexquad.cpp
  erohin.vladimir/T1/complexquad.hpp
  erohin.vladimir/T1/composite_shape.cpp
  erohin.vladimir/T1/composite_shape.hpp
  erohin.vladimir/T1/create_shape.cpp
  erohin.vladimir/T1/create_shape.hpp
  erohin.vladimir/T1/diamond.cpp
  erohin.vladimir/T1/diamond.hpp
  erohin.vladimir/T1/geom_func.cpp
  erohin.vladimir/T1/geom_func.hpp
  erohin.vladimir/T1/input_shape.cpp
  erohin.vladimir/T1/input_shape.hpp
  erohin.vladimir/T1/main.cpp
  erohin.vladimir/T1/output_shape.cpp
  erohin.vladimir/T1/output_shape.hpp
  erohin.vladimir/T1/rectangle.cpp
  erohin.vladimir/T1/rectangle.hpp
  erohin.vladimir/T1/shape.cpp
  erohin.vladimir/T1/shape.hpp
  erohin.vladimir/T1/triangle.cpp
  erohin.vladimir/T1/triangle.hpp
Labels: fine

#156 Nikitov.dmitriy/T1
  nikitov.dmitriy/T1/base-types.hpp
  nikitov.dmitriy/T1/composite_shape.cpp
  nikitov.dmitriy/T1/composite_shape.hpp
  nikitov.dmitriy/T1/diamond.cpp
  nikitov.dmitriy/T1/diamond.hpp
  nikitov.dmitriy/T1/input_array.cpp
  nikitov.dmitriy/T1/input_array.hpp
  nikitov.dmitriy/T1/main.cpp
  nikitov.dmitriy/T1/rectangle.cpp
  nikitov.dmitriy/T1/rectangle.hpp
  nikitov.dmitriy/T1/regular.cpp
  nikitov.dmitriy/T1/regular.hpp
  nikitov.dmitriy/T1/scale_figures.cpp
  nikitov.dmitriy/T1/scale_figures.hpp
  nikitov.dmitriy/T1/shape.cpp
  nikitov.dmitriy/T1/shape.hpp
Labels: fine

#158 zaitsev.vladimir/T1
  zaitsev.vladimir/T1/base-types.cpp
  zaitsev.vladimir/T1/base-types.hpp
  zaitsev.vladimir/T1/complexquad.cpp
  zaitsev.vladimir/T1/complexquad.hpp
  zaitsev.vladimir/T1/composite_shape.cpp
  zaitsev.vladimir/T1/composite_shape.hpp
  zaitsev.vladimir/T1/geometric_functions.cpp
  zaitsev.vladimir/T1/geometric_functions.hpp
  zaitsev.vladimir/T1/main.cpp
  zaitsev.vladimir/T1/parallelogram.cpp
  zaitsev.vladimir/T1/parallelogram.hpp
  zaitsev.vladimir/T1/rectangle.cpp
  zaitsev.vladimir/T1/rectangle.hpp
  zaitsev.vladimir/T1/shape.cpp
  zaitsev.vladimir/T1/shape.hpp
  zaitsev.vladimir/T1/shapes_i_o.cpp
  zaitsev.vladimir/T1/shapes_i_o.hpp
Labels: fine

#181 Serter.tugce/P1
  serter.tugce/P1/countOfSignsChangesInSeq.cpp
  serter.tugce/P1/countOfSignsChangesInSeq.hpp
  serter.tugce/P1/main.cpp
Labels: fine

#149 marishin.leonid/T1
  marishin.leonid/T1/base-types.hpp
  marishin.leonid/T1/checkTriangle.cpp
  marishin.leonid/T1/checkTriangle.hpp
  marishin.leonid/T1/displayoutput.cpp
  marishin.leonid/T1/displayoutput.hpp
  marishin.leonid/T1/inputshape.cpp
  marishin.leonid/T1/inputshape.hpp
  marishin.leonid/T1/main.cpp
  marishin.leonid/T1/rectangle.cpp
  marishin.leonid/T1/rectangle.hpp
  marishin.leonid/T1/ring.cpp
  marishin.leonid/T1/ring.hpp
  marishin.leonid/T1/scale.cpp
  marishin.leonid/T1/scale.hpp
  marishin.leonid/T1/scaleRectangle.cpp
  marishin.leonid/T1/scaleRectangle.hpp
  marishin.leonid/T1/shape.cpp
  marishin.leonid/T1/shape.hpp
  marishin.leonid/T1/triangle.cpp
  marishin.leonid/T1/triangle.hpp
  marishin.leonid/common/readArray.cpp
  marishin.leonid/common/readArray.hpp
Labels: fine, 3/5

#169 grechishnikov.roman/T1
  grechishnikov.roman/P3/inputStr.hpp
  grechishnikov.roman/P3/main.cpp
  grechishnikov.roman/T1/base-types.hpp
  grechishnikov.roman/T1/inputShapes.cpp
  grechishnikov.roman/T1/inputShapes.hpp
  grechishnikov.roman/T1/isoScale.cpp
  grechishnikov.roman/T1/isoScale.hpp
  grechishnikov.roman/T1/main.cpp
  grechishnikov.roman/T1/outputShapes.cpp
  grechishnikov.roman/T1/outputShapes.hpp
  grechishnikov.roman/T1/parametersLogic.cpp
  grechishnikov.roman/T1/parametersLogic.hpp
  grechishnikov.roman/T1/pointLogic.cpp
  grechishnikov.roman/T1/pointLogic.hpp
  grechishnikov.roman/T1/polygon.cpp
  grechishnikov.roman/T1/polygon.hpp
  grechishnikov.roman/T1/rectangle.cpp
  grechishnikov.roman/T1/rectangle.hpp
  grechishnikov.roman/T1/shape.cpp
  grechishnikov.roman/T1/shape.hpp
  grechishnikov.roman/T1/triangle.cpp
  grechishnikov.roman/T1/triangle.hpp
  grechishnikov.roman/common/inputString.cpp
  grechishnikov.roman/common/inputString.hpp
Labels: fine, 3/5

#146 rebdev.pavel/T1
  rebdev.pavel/T1/base-types.hpp
  rebdev.pavel/T1/concave.cpp
  rebdev.pavel/T1/concave.hpp
  rebdev.pavel/T1/figureFunction.cpp
  rebdev.pavel/T1/figureFunction.hpp
  rebdev.pavel/T1/figureInputFunction.cpp
  rebdev.pavel/T1/figureInputFunction.hpp
  rebdev.pavel/T1/main.cpp
  rebdev.pavel/T1/outputShapes.cpp
  rebdev.pavel/T1/outputShapes.hpp
  rebdev.pavel/T1/polygon.cpp
  rebdev.pavel/T1/polygon.hpp
  rebdev.pavel/T1/rectangle.cpp
  rebdev.pavel/T1/rectangle.hpp
  rebdev.pavel/T1/shape.cpp
  rebdev.pavel/T1/shape.hpp
Labels: fine, 3/5

#167 sivkov.filipp/T1
  sivkov.filipp/T1/base-types.hpp
  sivkov.filipp/T1/complexquad.cpp
  sivkov.filipp/T1/complexquad.hpp
  sivkov.filipp/T1/concave.cpp
  sivkov.filipp/T1/concave.hpp
  sivkov.filipp/T1/inputShape.cpp
  sivkov.filipp/T1/inputShape.hpp
  sivkov.filipp/T1/main.cpp
  sivkov.filipp/T1/othersFun.cpp
  sivkov.filipp/T1/othersFun.hpp
  sivkov.filipp/T1/output.cpp
  sivkov.filipp/T1/output.hpp
  sivkov.filipp/T1/rectangle.cpp
  sivkov.filipp/T1/rectangle.hpp
  sivkov.filipp/T1/shape.hpp
Labels: 2/5

#171 isaychev.vladislav/T1
  isaychev.vladislav/P3/inputString.cpp
  isaychev.vladislav/P3/inputString.hpp
  isaychev.vladislav/P3/main.cpp
  isaychev.vladislav/T1/base-types.hpp
  isaychev.vladislav/T1/circle.cpp
  isaychev.vladislav/T1/circle.hpp
  isaychev.vladislav/T1/compositeShape.cpp
  isaychev.vladislav/T1/compositeShape.hpp
  isaychev.vladislav/T1/creatingFigures.cpp
  isaychev.vladislav/T1/creatingFigures.hpp
  isaychev.vladislav/T1/geometryFunctions.cpp
  isaychev.vladislav/T1/geometryFunctions.hpp
  isaychev.vladislav/T1/isoscale.cpp
  isaychev.vladislav/T1/isoscale.hpp
  isaychev.vladislav/T1/main.cpp
  isaychev.vladislav/T1/outputResults.cpp
  isaychev.vladislav/T1/outputResults.hpp
  isaychev.vladislav/T1/rectangle.cpp
  isaychev.vladislav/T1/rectangle.hpp
  isaychev.vladislav/T1/regular.cpp
  isaychev.vladislav/T1/regular.hpp
  isaychev.vladislav/T1/shape.cpp
  isaychev.vladislav/T1/shape.hpp
  isaychev.vladislav/T1/stringManipulations.cpp
  isaychev.vladislav/T1/stringManipulations.hpp
  isaychev.vladislav/common/inputString.cpp
  isaychev.vladislav/common/inputString.hpp
Labels: fine, 4/5

#177 zakozhurnikova.kristina/T1
  zakozhurnikova.kristina/P3/main.cpp
  zakozhurnikova.kristina/P3/removeSpaces.cpp
  zakozhurnikova.kristina/P3/stringOperations.cpp
  zakozhurnikova.kristina/P3/stringOperations.h
  zakozhurnikova.kristina/T1/base-types.hpp
  zakozhurnikova.kristina/T1/complexquad.cpp
  zakozhurnikova.kristina/T1/complexquad.hpp
  zakozhurnikova.kristina/T1/diamond.cpp
  zakozhurnikova.kristina/T1/diamond.hpp
  zakozhurnikova.kristina/T1/geometryFunc.cpp
  zakozhurnikova.kristina/T1/geometryFunc.hpp
  zakozhurnikova.kristina/T1/isoScale.cpp
  zakozhurnikova.kristina/T1/isoScale.hpp
  zakozhurnikova.kristina/T1/main.cpp
  zakozhurnikova.kristina/T1/outputOperations.cpp
  zakozhurnikova.kristina/T1/outputOperations.hpp
  zakozhurnikova.kristina/T1/rectangle.cpp
  zakozhurnikova.kristina/T1/rectangle.hpp
  zakozhurnikova.kristina/T1/shape.cpp
  zakozhurnikova.kristina/T1/shape.hpp
  zakozhurnikova.kristina/T1/shapesArrayOperations.cpp
  zakozhurnikova.kristina/T1/shapesArrayOperations.hpp
  zakozhurnikova.kristina/T1/square.cpp
  zakozhurnikova.kristina/T1/square.hpp
  zakozhurnikova.kristina/common/inputOperations.cpp
  zakozhurnikova.kristina/common/inputOperations.hpp
Labels: fine, 2/5

#180 lebedev.anton/T1
  lebedev.anton/T1/base-functions.cpp
  lebedev.anton/T1/base-functions.hpp
  lebedev.anton/T1/base-types.hpp
  lebedev.anton/T1/complexquad.cpp
  lebedev.anton/T1/complexquad.hpp
  lebedev.anton/T1/diamond.cpp
  lebedev.anton/T1/diamond.hpp
  lebedev.anton/T1/input_output.cpp
  lebedev.anton/T1/input_output.hpp
  lebedev.anton/T1/iso_scale.cpp
  lebedev.anton/T1/iso_scale.hpp
  lebedev.anton/T1/main.cpp
  lebedev.anton/T1/parallelogram.cpp
  lebedev.anton/T1/parallelogram.hpp
  lebedev.anton/T1/rectangle.cpp
  lebedev.anton/T1/rectangle.hpp
  lebedev.anton/T1/shape.cpp
  lebedev.anton/T1/shape.hpp
Labels: fine, 2/5

#166 arakelyan.daniil/T1
  arakelyan.daniil/P3/main.cpp
  arakelyan.daniil/T1/base-types.hpp
  arakelyan.daniil/T1/diamond.cpp
  arakelyan.daniil/T1/diamond.hpp
  arakelyan.daniil/T1/inputAndOutputOperations.cpp
  arakelyan.daniil/T1/inputAndOutputOperations.hpp
  arakelyan.daniil/T1/main.cpp
  arakelyan.daniil/T1/parallelogram.cpp
  arakelyan.daniil/T1/parallelogram.hpp
  arakelyan.daniil/T1/rectangle.cpp
  arakelyan.daniil/T1/rectangle.hpp
  arakelyan.daniil/T1/scaleOperations.cpp
  arakelyan.daniil/T1/scaleOperations.hpp
  arakelyan.daniil/T1/shape-creation.cpp
  arakelyan.daniil/T1/shape-creation.hpp
  arakelyan.daniil/T1/shape.cpp
  arakelyan.daniil/T1/shape.hpp
  arakelyan.daniil/common/inputLine.cpp
  arakelyan.daniil/common/inputLine.hpp
Labels: fine, 3/5

#189 balashov.artem/P0
  balashov.artem/P0/main.cpp
Labels: fine

#192 prisyach.andrey/P0
  prisyach.andrey/P0/main.cpp
Labels: fine
