Repository Volgarenok/spbspu-labs-2023-aap-a, pull requests merged in 2024-03, with the labels that each got.

#191 serter.tugce/P4
  serter.tugce/P4/findRowThatHasABigSeries.cpp
  serter.tugce/P4/findRowThatHasABigSeries.hpp
  serter.tugce/P4/main.cpp
  serter.tugce/P4/readMatrix.cpp
  serter.tugce/P4/readMatrix.hpp
Labels: fine

#184 agarkov.sergey/P1
  agarkov.sergey/P1/DivWithoutRemCounter.cpp
  agarkov.sergey/P1/DivWithoutRemCounter.hpp
  agarkov.sergey/P1/PythTripleCounter.cpp
  agarkov.sergey/P1/PythTripleCounter.hpp
  agarkov.sergey/P1/main.cpp
Labels: fine

#183 Shabalin.dmitrij/p4
  shabalin.dmitrij/P4/findLargeSeriesofElements.cpp
  shabalin.dmitrij/P4/findLargeSeriesofElements.hpp
  shabalin.dmitrij/P4/ioprocessing.cpp
  shabalin.dmitrij/P4/ioprocessing.hpp
  shabalin.dmitrij/P4/main.cpp
  shabalin.dmitrij/P4/makeUpSmoothMatrix.cpp
  shabalin.dmitrij/P4/makeUpSmoothMatrix.hpp
Labels: fine

#175 vyzhanov.daniil/P3
  vyzhanov.daniil/P3/CountUniqueLetters.cpp
  vyzhanov.daniil/P3/CountUniqueLetters.hpp
  vyzhanov.daniil/P3/DeleteAllNumbers.cpp
  vyzhanov.daniil/P3/DeleteAllNumbers.hpp
  vyzhanov.daniil/P3/InputString.cpp
  vyzhanov.daniil/P3/InputString.hpp
  vyzhanov.daniil/P3/main.cpp
Labels: fine

#193 agarkov.sergey/P4
  agarkov.sergey/P4/isUpperTriangularMatrix.cpp
  agarkov.sergey/P4/isUpperTriangularMatrix.hpp
  agarkov.sergey/P4/main.cpp
  agarkov.sergey/P4/transformMatrixAPeriph.cpp
  agarkov.sergey/P4/transformMatrixAPeriph.hpp
Labels: fine

#185 petuhov.kirill/P3
  petuhov.kirill/P3/main.cpp
  petuhov.kirill/P3/removespaces.cpp
  petuhov.kirill/P3/removespaces.hpp
  petuhov.kirill/P3/streamtostring.cpp
  petuhov.kirill/P3/streamtostring.hpp
  petuhov.kirill/P3/substractstring.cpp
  petuhov.kirill/P3/substractstring.hpp
Labels: fine

#178 skuratov.danil/T1
  skuratov.danil/T1/base-types.hpp
  skuratov.danil/T1/diamond.cpp
  skuratov.danil/T1/diamond.hpp
  skuratov.danil/T1/inputOutPutShapes.cpp
  skuratov.danil/T1/inputOutputShapes.hpp
  skuratov.danil/T1/isoScale.cpp
  skuratov.danil/T1/isoScale.hpp
  skuratov.danil/T1/main.cpp
  skuratov.danil/T1/parallelogram.cpp
  skuratov.danil/T1/parallelogram.hpp
  skuratov.danil/T1/rectangle.cpp
  skuratov.danil/T1/rectangle.hpp
  skuratov.danil/T1/shape.hpp
  skuratov.danil/T1/square.cpp
  skuratov.danil/T1/square.hpp
Labels: fine, 3/5

#179 ishmuratov.eric/T1
  ishmuratov.eric/T1/base-types.hpp
  ishmuratov.eric/T1/concave.cpp
  ishmuratov.eric/T1/concave.hpp
  ishmuratov.eric/T1/data_process.cpp
  ishmuratov.eric/T1/data_process.hpp
  ishmuratov.eric/T1/diamond.cpp
  ishmuratov.eric/T1/diamond.hpp
  ishmuratov.eric/T1/input.cpp
  ishmuratov.eric/T1/input.hpp
  ishmuratov.eric/T1/main.cpp
  ishmuratov.eric/T1/output.cpp
  ishmuratov.eric/T1/output.hpp
  ishmuratov.eric/T1/rectangle.cpp
  ishmuratov.eric/T1/rectangle.hpp
  ishmuratov.eric/T1/shape.hpp
  ishmuratov.eric/T1/triangle.cpp
  ishmuratov.eric/T1/triangle.hpp
Labels: fine, 3/5

#170 chistyakov.vladislav/T1
  chistyakov.vladislav/T1/base-types.hpp
  chistyakov.vladislav/T1/complexquad.cpp
  chistyakov.vladislav/T1/complexquad.hpp
  chistyakov.vladislav/T1/inputShapes.cpp
  chistyakov.vladislav/T1/inputShapes.hpp
  chistyakov.vladislav/T1/isotropScale.cpp
  chistyakov.vladislav/T1/isotropScale.hpp
  chistyakov.vladislav/T1/main.cpp
  chistyakov.vladislav/T1/outputShape.cpp
  chistyakov.vladislav/T1/outputShape.hpp
  chistyakov.vladislav/T1/rectangle.cpp
  chistyakov.vladislav/T1/rectangle.hpp
  chistyakov.vladislav/T1/shape.hpp
  chistyakov.vladislav/T1/square.cpp
  chistyakov.vladislav/T1/square.hpp
Labels: fine, 3/5

#182 lopatina.sofia/T1
  lopatina.sofia/T1/base-types.hpp
  lopatina.sofia/T1/del_out_functions.cpp
  lopatina.sofia/T1/del_out_functions.hpp
  lopatina.sofia/T1/diamond.cpp
  lopatina.sofia/T1/diamond.hpp
  lopatina.sofia/T1/isoscale.cpp
  lopatina.sofia/T1/isoscale.hpp
  lopatina.sofia/T1/main.cpp
  lopatina.sofia/T1/rectangle.cpp
  lopatina.sofia/T1/rectangle.hpp
  lopatina.sofia/T1/shape.hpp
  lopatina.sofia/T1/square.cpp
  lopatina.sofia/T1/square.hpp
  lopatina.sofia/T1/triangle.cpp
  lopatina.sofia/T1/triangle.hpp
Labels: fine, 3/5

#139 Vojuck.victoria/p1
  vojuck.victoria/P1/aftmax.cpp
  vojuck.victoria/P1/aftmax.hpp
  vojuck.victoria/P1/main.cpp
  vojuck.victoria/P1/samemin.cpp
  vojuck.victoria/P1/samemin.hpp
Labels: fine, 4/5

#102 sakovskaia.maiia/P4
  sakovskaia.maiia/P4/main.cpp
  sakovskaia.maiia/P4/matrix.hpp
  sakovskaia.maiia/P4/matrix_counter.cpp
  sakovskaia.maiia/P4/matrix_input_res.hpp
  sakovskaia.maiia/P4/matrix_io.cpp
Labels: fine

#154 belokurskaya.sofia/T1
  belokurskaya.sofia/T1/base-types.hpp
  belokurskaya.sofia/T1/concave.cpp
  belokurskaya.sofia/T1/concave.hpp
  belokurskaya.sofia/T1/iso_scale.cpp
  belokurskaya.sofia/T1/iso_scale.hpp
  belokurskaya.sofia/T1/main.cpp
  belokurskaya.sofia/T1/reader.hpp
  belokurskaya.sofia/T1/rectangle.cpp
  belokurskaya.sofia/T1/rectangle.hpp
  belokurskaya.sofia/T1/results_printer.cpp
  belokurskaya.sofia/T1/results_printer.hpp
  belokurskaya.sofia/T1/shape.hpp
  belokurskaya.sofia/T1/triangle.cpp
  belokurskaya.sofia/T1/triangle.hpp
Labels: fine, 3/5

#73 Poleleyko.ivan/p1
  poleleyko.ivan/P1/main.cpp
Labels: fine, 3/5

#163 sakovskaia.maiia/P3
  sakovskaia.maiia/P3/main.cpp
  sakovskaia.maiia/P3/string_analysis.cpp
  sakovskaia.maiia/P3/string_analysis.hpp
  sakovskaia.maiia/P3/string_reader.cpp
  sakovskaia.maiia/P3/string_reader.hpp
Labels: fine

#194 Vyzhanov.daniil/T1
  vyzhanov.daniil/T1/base-types.hpp
  vyzhanov.daniil/T1/doScale.cpp
  vyzhanov.daniil/T1/doScale.hpp
  vyzhanov.daniil/T1/input.cpp
  vyzhanov.daniil/T1/input.hpp
  vyzhanov.daniil/T1/main.cpp
  vyzhanov.daniil/T1/output.cpp
  vyzhanov.daniil/T1/output.hpp
  vyzhanov.daniil/T1/rectangle.cpp
  vyzhanov.daniil/T1/rectangle.hpp
  vyzhanov.daniil/T1/regular.cpp
  vyzhanov.daniil/T1/regular.hpp
  vyzhanov.daniil/T1/shape.cpp
  vyzhanov.daniil/T1/shape.hpp
  vyzhanov.daniil/T1/square.cpp
  vyzhanov.daniil/T1/square.hpp
  vyzhanov.daniil/T1/triangle.cpp
  vyzhanov.daniil/T1/triangle.hpp
Labels: fine, 3/5

#188 stepanov.gena/T1
  stepanov.gena/T1/base-types.hpp
  stepanov.gena/T1/circle.cpp
  stepanov.gena/T1/circle.hpp
  stepanov.gena/T1/ellipse.cpp
  stepanov.gena/T1/ellipse.hpp
  stepanov.gena/T1/input_output_shapes.cpp
  stepanov.gena/T1/input_output_shapes.hpp
  stepanov.gena/T1/isoScale.cpp
  stepanov.gena/T1/isoScale.hpp
  stepanov.gena/T1/main.cpp
  stepanov.gena/T1/rectangle.cpp
  stepanov.gena/T1/rectangle.hpp
  stepanov.gena/T1/shape.cpp
  stepanov.gena/T1/shape.hpp
  stepanov.gena/T1/square.cpp
  stepanov.gena/T1/square.hpp
Labels: fine, 3/5

#205 Prisyach.andrey/p1
  prisyach.andrey/P1/loc_max_counter.cpp
  prisyach.andrey/P1/loc_max_counter.hpp
  prisyach.andrey/P1/main.cpp
  prisyach.andrey/P1/sum_dup_counter.cpp
  prisyach.andrey/P1/sum_dup_counter.hpp
Labels: fine

#198 Vojuck.victoria/p4
  vojuck.victoria/P4/findMaxSum.cpp
  vojuck.victoria/P4/findMaxSum.hpp
  vojuck.victoria/P4/inputMatrix.cpp
  vojuck.victoria/P4/inputMatrix.hpp
  vojuck.victoria/P4/isUpperTriangular.cpp
  vojuck.victoria/P4/isUpperTriangular.hpp
  vojuck.victoria/P4/main.cpp
Labels: fine

#196 skopchenko.alexander/p4
  skopchenko.alexander/P4/input.cpp
  skopchenko.alexander/P4/input.h
  skopchenko.alexander/P4/main.cpp
  skopchenko.alexander/P4/output.cpp
  skopchenko.alexander/P4/output.h
  skopchenko.alexander/P4/smoothed.cpp
  skopchenko.alexander/P4/smoothed.h
  skopchenko.alexander/P4/topclock.cpp
  skopchenko.alexander/P4/topclock.h
Labels: fine, 3/5
